import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavgationBar/NavBar";
import Footer from "./components/Footer/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          toastOptions={{
            style: { background: "rgb(0,0,255)", color: "#fff" },
            duration: 3000, // Optional: Control how long the toast is visible
          }}
          position="top-center" // Position the toast
          reverseOrder={false} // This will keep the order of toasts
        />
        <div className="flex flex-col min-h-screen">
          <NavBar />
          <main className="flex-grow  ">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
