export const fieldsOfStudy = [
  "Accounting",
  "Aerospace Engineering",
  "Agriculture",
  "Anthropology",
  "Applied Mathematics",
  "Architecture",
  "Art and Design",
  "Astronomy",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Communication Studies",
  "Computer Science",
  "Criminal Justice",
  "Culinary Arts",
  "Data Science",
  "Dentistry",
  "Digital Media",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "Environmental Science",
  "Fashion Design",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Geography",
  "Geology",
  "Graphic Design",
  "Health Administration",
  "History",
  "Hospitality Management",
  "Human Resources",
  "Information Technology",
  "International Relations",
  "Journalism",
  "Law",
  "Linguistics",
  "Marketing",
  "Mechanical Engineering",
  "Medicine",
  "Microbiology",
  "Music",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Religious Studies",
  "Sociology",
  "Software Engineering",
  "Sports Management",
  "Statistics",
  "Theater",
  "Urban Planning",
  "Veterinary Medicine",
  "Zoology",
];
